= Real-Time Metal Surface Defect Detection with Improved YOLOv8

= Abstract

Metal surface defect detection in real industrial environments remains challenging because tiny defects are easily submerged by complex texture backgrounds, low-contrast defect regions are difficult to localize, and practical deployment imposes strict latency and resource constraints. This study develops an improved YOLOv8-based detection framework for real-time metallic surface inspection across public and self-built datasets. The proposed workflow is organized around three principles: shallow structural detail preservation, high-resolution defect-sensitive feature enhancement, and cross-dataset transfer from public benchmarks to a real industrial port_defect dataset. The evaluation protocol jointly considers NEU DET, GC10 DET, and port_defect, and reports accuracy, complexity, runtime efficiency, and deployment-oriented behavior under a unified experimental setting. The current manuscript serves as the project draft skeleton and is designed to be refined with the final quantitative results, ablation findings, and deployment logs generated by the training and validation pipeline.

= Introduction

Automatic surface defect detection is a key component of intelligent industrial inspection, especially in steel and metallic production lines that demand high throughput and stable product quality. Compared with general object detection tasks, metallic surface inspection often exhibits stronger background regularity, higher texture similarity between defects and normal regions, and a larger proportion of small or elongated targets. These characteristics make it difficult for standard real-time detectors to maintain both high sensitivity and low false-alarm rates in practical scenes.

YOLOv8 provides a strong real-time baseline for industrial vision tasks because of its efficient architecture and mature deployment ecosystem. However, when it is directly applied to metallic surface defect detection, performance degradation can still appear in cases involving weak boundaries, tiny targets, and cross-domain data shifts between public datasets and real production images. This motivates the present study, which aims to improve YOLOv8 while preserving its deployment advantages.

The research focus of this project is aligned with three datasets: NEU DET, GC10 DET, and a self-built port_defect dataset. NEU DET provides controlled steel defect samples with clear industrial relevance. GC10 DET introduces larger appearance variation and stronger inter-class similarity. The port_defect dataset is used to verify whether improvements learned from public data can transfer to the target industrial scene. On this basis, the paper emphasizes not only benchmark accuracy but also transferability and deployment readiness.

The main goal of this work is therefore to establish a complete technical loop for industrial defect inspection: improved YOLOv8 design, public-dataset pretraining, real-scene transfer learning, ablation analysis, and deployment-oriented evaluation. The current draft is structured to support that loop and can be incrementally updated as model modules, training logs, and deployment reports become available in the workspace.

= Methods

== Problem Formulation

This work addresses metallic surface defect detection under realistic industrial constraints. Given an input image from a metallic surface inspection pipeline, the detector must identify defect categories and localize corresponding regions in real time. The main technical challenges include high-texture background interference, weak edge contrast, small target scale, and domain shift between public datasets and the real industrial environment.

== Baseline Detector

YOLOv8 is adopted as the baseline detector because it provides a practical balance between detection accuracy, model compactness, and deployment maturity. Its one-stage design is well suited to high-throughput production settings, and it offers a convenient starting point for lightweight structural modification, transfer learning, and downstream export to accelerated inference backends.

== Improved YOLOv8 Design

The proposed detector is built around lightweight modifications that strengthen feature representation for metallic surface inspection. First, shallow-stage structural cues are emphasized so that fine edges and local defect contours can be retained more effectively in the presence of dense texture backgrounds. Second, the high-resolution detection path is enhanced to improve the representation of tiny or texture-similar defects. Third, the multi-scale aggregation process is adjusted to better preserve defect-sensitive details without introducing excessive computational burden.

At the current draft stage, these improvements are described at the design level rather than fixed to a single implementation detail. This keeps the manuscript consistent with the evolving codebase while allowing the final version to insert the exact module names, layer positions, and ablation results after implementation stabilizes.

== Transfer Learning Strategy

The training workflow begins with public-dataset learning on NEU DET and GC10 DET. This stage allows the detector to acquire general metallic defect priors, including crack-like patterns, patches, inclusions, rolled-in scale, and other texture-related irregularities. The model is then fine-tuned on port_defect so that the learned representation adapts to the specific appearance, background complexity, and acquisition conditions of the target industrial scene.

Progressive transfer is adopted as the preferred setting. In the early fine-tuning stage, generic features learned from public data can be retained more strongly, while later optimization updates the full detector to bridge the domain gap. This design is intended to improve data efficiency for the self-built dataset and reduce overfitting to limited real-scene samples.

== Deployment-Oriented Optimization

The study is not limited to offline accuracy improvement. The detector is also designed for practical export and deployment, including model complexity control, runtime analysis, and compatibility with later inference acceleration steps such as ONNX export or TensorRT-oriented testing. This allows the final paper to discuss industrial applicability in addition to algorithmic effectiveness.

= Results

== Experimental Protocol

The experimental evaluation follows a unified protocol across NEU DET, GC10 DET, and port_defect. The core metrics include Precision, Recall, mAP@0.5, and mAP@0.5:0.95 for detection quality, together with parameter count, FLOPs, model size, latency, and FPS for deployment-oriented analysis. The final version of this section will be populated directly from the training logs, validation reports, and analysis artifacts generated by the project pipeline.

== Baseline and Comparative Performance

The baseline comparison section is organized around the standard YOLOv8 detector and the improved YOLOv8 variant proposed in this study. Additional comparison models may be incorporated as the experiment scripts are finalized. The narrative focus will be placed on whether the proposed improvements increase sensitivity to small defects and weak boundaries without causing unacceptable runtime overhead.

== Ablation Analysis

Ablation experiments will be used to isolate the contribution of each modification introduced into the detector. The intended structure includes single-module evaluation, combined-module evaluation, and a discussion of whether accuracy gains remain stable across public and self-built datasets. This section should ultimately connect each architectural choice to an observable gain in detection quality, robustness, or efficiency.

== Cross-Dataset Transfer and Deployment Evaluation

The transfer evaluation is centered on the effect of pretraining with NEU DET and GC10 DET before fine-tuning on port_defect. The final manuscript should discuss whether this strategy improves convergence stability, localization quality, and generalization to complex industrial backgrounds. In parallel, deployment evaluation will summarize model size, runtime, and export behavior in the target inference environment.

= Discussion

The expected contribution of this work lies in showing that industrially useful metallic defect detection requires more than an isolated benchmark gain. A detector intended for production deployment should be analyzed from the perspectives of feature sensitivity, domain adaptation, computational efficiency, and exportability. This broader framing is particularly important when the target defects are small, weakly contrasted, and visually close to the surrounding background texture.

Another important point is that public datasets and real industrial datasets play complementary roles. Public benchmarks support reproducible comparison and initial feature learning, while the self-built port_defect dataset reveals the actual deployment difficulty. The combination of the two makes it possible to judge whether an improved detector is merely tuned to a benchmark or genuinely adaptable to a production scenario.

The current limitations of the draft are mainly related to incomplete experiment-specific details. Exact module definitions, dataset statistics, and final quantitative values should be inserted only after the implementation and validation stages converge. This manuscript therefore functions as a stable writing scaffold that can absorb later results without changing the central research logic.

= Conclusion

This paper draft proposes a complete research framework for real-time metal surface defect detection based on an improved YOLOv8 detector. The central idea is to enhance shallow structural cues, strengthen high-resolution defect representation, and combine public-dataset pretraining with transfer learning to a self-built industrial dataset. The study further emphasizes deployment-oriented evaluation so that the final result is meaningful for practical inspection systems rather than benchmark performance alone.

As the project proceeds, the manuscript can be updated with final model details, quantitative comparison tables, ablation results, transfer-learning evidence, and deployment logs. With those additions, the draft is expected to evolve naturally into a submission-oriented paper for industrial image processing or real-time vision venues.
